# Generated by Django 2.2.7 on 2020-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.IntegerField()),
                ('appid', models.IntegerField()),
            ],
        ),
    ]
