# Generated by Django 2.2.7 on 2020-01-19 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamechange',
            name='appid',
        ),
        migrations.AddField(
            model_name='gamechange',
            name='changelog',
            field=models.CharField(default=None, max_length=264),
        ),
        migrations.AddField(
            model_name='gamechange',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamechange',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
