# Generated by Django 2.2.7 on 2020-01-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200119_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('WINDOWS', 'Windows'), ('MACOS', 'MacOS'), ('LINUX', 'Linux')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='os',
            field=models.ManyToManyField(to='game.OSOptions'),
        ),
    ]
