# Generated by Django 2.2.7 on 2020-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200126_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clienticon',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='clienttga',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_small',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_state',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
