# Generated by Django 2.2.7 on 2020-02-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200228_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='app_type',
            field=models.ManyToManyField(to='game.AppType'),
        ),
    ]
