# Generated by Django 2.2.7 on 2020-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20200304_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic_fullurl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic_score',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
