# Generated by Django 2.2.7 on 2020-03-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20200305_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='steam_release_date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
