# Generated by Django 2.2.7 on 2020-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20200305_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='steam_release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
