# Generated by Django 2.2.7 on 2020-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20200308_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='clienticon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='community_hub_visible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='community_visible_stats',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo_small',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic_fullurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic_score',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='review_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='review_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='workshop_visible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
