DEBUG = False

ALLOWED_HOSTS = ['steamcomparer.com', 'gamecomparer.com', '165.227.56.2']

CORS_ORIGIN_ALLOW_ALL = False

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SITE_ID = 2
