# Generated by Django 2.2.7 on 2020-01-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200128_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamechange',
            old_name='change_id',
            new_name='change_number',
        ),
        migrations.AddField(
            model_name='gamechange',
            name='action',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
