# Generated by Django 2.2.7 on 2020-02-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200228_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='languages',
            new_name='supported_languages',
        ),
    ]
