# Generated by Django 2.2.7 on 2020-03-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20200305_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='community_hub_visible',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='community_visible_stats',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='review_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='workshop_visible',
            field=models.BooleanField(null=True),
        ),
    ]
