# Generated by Django 2.2.7 on 2020-07-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20200702_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('changenumber', models.IntegerField()),
                ('action', models.CharField(choices=[('new', 'new app'), ('existing', 'existing app')], default='new', max_length=32)),
            ],
        ),
    ]
