# Generated by Django 2.2.7 on 2020-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
